FROM node:18-alpine as build

ARG VITE_STRAPI_URL
ARG VITE_STRAPI_TOKEN

WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm ci

COPY . /app

RUN npm run build

EXPOSE 5173

FROM nginx:1.21.0-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]